added other npa

diff --git a/.github/workflows/terra_rm.yaml b/.github/workflows/terra_rm.yaml
--- a/.github/workflows/terra_rm.yaml
+++ b/.github/workflows/terra_rm.yaml
@@ -274,9 +274,27 @@ jobs:
           --output json > rm_outputs.json
 
           WEB_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
+          CMS_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
+          WEB_TO_CMS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_to_cms_npa_test_id") | ."output-value"' rm_outputs.json)
+          CMS_TO_WEB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_to_web_npa_test_id") | ."output-value"' rm_outputs.json)
           NET_COMPARTMENT_ID=$(jq -r '.data.items[] | select(."output-name"=="net_compartment_id") | ."output-value"' rm_outputs.json)
 
           if [ -z "${WEB_TO_DB_NPA_TEST_ID}" ]  = "null" ]; then
+            echo "ERROR: output web_to_db_npa_test_id not found"
+            exit 1
+          fi
+
+          if [ -z "${CMS_TO_DB_NPA_TEST_ID}" ]  = "null" ]; then
+            echo "ERROR: output web_to_db_npa_test_id not found"
+            exit 1
+          fi
+
+          if [ -z "${WEB_TO_CMS_NPA_TEST_ID}" ]  = "null" ]; then
+            echo "ERROR: output web_to_db_npa_test_id not found"
+            exit 1
+          fi
+
+          if [ -z "${CMS_TO_WEB_NPA_TEST_ID}" ]  = "null" ]; then
             echo "ERROR: output web_to_db_npa_test_id not found"
             exit 1
           fi
@@ -288,6 +306,12 @@ jobs:
 
           echo "web_to_db_npa_test_id=${WEB_TO_DB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
 
+          echo "web_to_db_npa_test_id=${CMS_TO_DB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
+
+          echo "web_to_db_npa_test_id=${WEB_TO_CMS_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
+
+          echo "web_to_db_npa_test_id=${CMS_TO_WEB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
+
           echo "net_compartment_id=${NET_COMPARTMENT_ID}" >> "$GITHUB_OUTPUT"
 
           echo "net_compartment_id=${NET_COMPARTMENT_ID}" >> "$GITHUB_ENV"
@@ -296,14 +320,16 @@ jobs:
         # shell: bash
         env:
           WEB_TO_DB_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.web_to_db_npa_test_id }}
+          CMS_TO_DB_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.cms_to_db_npa_test_id }}
+          WEB_TO_CMS_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.web_to_cms_npa_test_id }}
+          CMS_TO_WEB_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.cms_to_web_npa_test_id }}
           OCI_COMPARTMENT_OCID: ${{ steps.get_rm_outputs.outputs.net_compartment_id }}
           SUPPRESS_LABEL_WARNING: "True"
         run: |
           set -euo pipefail
 
-          echo "Running saved NPA test: ${WEB_TO_DB_NPA_TEST_ID}"
+          echo "Running saved NPA test for WEB-to-DB: ${WEB_TO_DB_NPA_TEST_ID}"
           
-
           oci vn-monitoring path-analysis get-path-analysis-persisted \
             --path-analyzer-test-id "${WEB_TO_DB_NPA_TEST_ID}" \
             --wait-for-state SUCCEEDED \
@@ -320,56 +346,123 @@ jobs:
             --limit 1 \
             --query 'data.items[0].id' \
             --raw-output)
-
-          
-          # if [ -z "${WR_ID}" ] || [ "${WR_ID}" = "null" ]; then
-          #   echo "ERROR: no VN Monitoring work request found in compartment"
-          #   exit 1
-          # fi
-          
-          # echo "Work request ID: ${WR_ID}"
-
+        
           WR_STATUS=$(oci vn-monitoring work-request get \
             --work-request-id "${WR_ID}" \
             --query 'data.status' \
             --raw-output)
 
-          # echo "Work request status: ${WR_STATUS}"
+          oci vn-monitoring work-request-result list \
+            --work-request-id "${WR_ID}"\
+            --all \
+            --result-type PATH_ANALYSIS \
+            --output json > web_to_db_npa_result.json
 
+          grep reachability web_to_db_npa_result.json
 
-          # if [ "${WR_STATUS}" != "SUCCEEDED" ]; then
-          #   echo "ERROR: Unreachable";
-          # else
-          #   echo "Reachable"
-          #   # oci vn-monitoring work-request-error list \
-          #   #   --work-request-id "${WR_ID}" \
-          #   #   --output json || true
-          #   # exit 1
-          # fi
+          ###############################
+          echo "Running saved NPA test for CMS-to-DB: ${CMS_TO_DB_NPA_TEST_ID}"
+          
+          oci vn-monitoring path-analysis get-path-analysis-persisted \
+            --path-analyzer-test-id "${CMS_TO_DB_NPA_TEST_ID}" \
+            --wait-for-state SUCCEEDED \
+            --wait-for-state FAILED \
+            --max-wait-seconds 900 \
+            --output json > path_run.json
 
-
+          
+          WR_ID=$(oci vn-monitoring work-request list \
+            --compartment-id "${OCI_COMPARTMENT_OCID}" \
+            --resource-id "${CMS_TO_DB_NPA_TEST_ID}" \
+            --sort-by timeAccepted \
+            --sort-order DESC \
+            --limit 1 \
+            --query 'data.items[0].id' \
+            --raw-output)
+        
+          WR_STATUS=$(oci vn-monitoring work-request get \
+            --work-request-id "${WR_ID}" \
+            --query 'data.status' \
+            --raw-output)
 
           oci vn-monitoring work-request-result list \
             --work-request-id "${WR_ID}"\
             --all \
             --result-type PATH_ANALYSIS \
-            --output json > path_result.json
+            --output json > cms_to_db_npa_result.json
+            
+          grep reachability cms_to_db_npa_result.json
+          #####################################
 
-          # echo "Reachability statuses:"
+          ###############################
+          echo "Running saved NPA test for WEB-to-CMS: ${WEB_TO_CMS_NPA_TEST_ID}"
           
-          grep reachability path_result.json
+          oci vn-monitoring path-analysis get-path-analysis-persisted \
+            --path-analyzer-test-id "${WEB_TO_CMS_NPA_TEST_ID}" \
+            --wait-for-state SUCCEEDED \
+            --wait-for-state FAILED \
+            --max-wait-seconds 900 \
+            --output json > path_run.json
 
-          # if jq -e '
-          #   [.. | .reachabilityStatus? // empty] as $s
-          #   | ($s | length) > 0 and ($s | all(. == "REACHABLE"))
-          # ' path_result.json > /dev/null; then
-          #   echo "REACHABLE"
-          # else
-          #   echo "UNREACHABLE"
-          #   jq -r '.. | .routeAnalysisDescription? // empty' path_result.json || true
-          # fi
+          
+          WR_ID=$(oci vn-monitoring work-request list \
+            --compartment-id "${OCI_COMPARTMENT_OCID}" \
+            --resource-id "${WEB_TO_CMS_NPA_TEST_ID}" \
+            --sort-by timeAccepted \
+            --sort-order DESC \
+            --limit 1 \
+            --query 'data.items[0].id' \
+            --raw-output)
+        
+          WR_STATUS=$(oci vn-monitoring work-request get \
+            --work-request-id "${WR_ID}" \
+            --query 'data.status' \
+            --raw-output)
+
+          oci vn-monitoring work-request-result list \
+            --work-request-id "${WR_ID}"\
+            --all \
+            --result-type PATH_ANALYSIS \
+            --output json > web_to_cms_npa_result.json
+            
+          grep reachability web_to_cms_npa_result.json
+          #####################################
+          ###############################
+          echo "Running saved NPA test for CMS-to-DB: ${CMS_TO_WEB_NPA_TEST_ID}"
+          
+          oci vn-monitoring path-analysis get-path-analysis-persisted \
+            --path-analyzer-test-id "${CMS_TO_WEB_NPA_TEST_ID}" \
+            --wait-for-state SUCCEEDED \
+            --wait-for-state FAILED \
+            --max-wait-seconds 900 \
+            --output json > path_run.json
+
+          
+          WR_ID=$(oci vn-monitoring work-request list \
+            --compartment-id "${OCI_COMPARTMENT_OCID}" \
+            --resource-id "${CMS_TO_WEB_NPA_TEST_ID}" \
+            --sort-by timeAccepted \
+            --sort-order DESC \
+            --limit 1 \
+            --query 'data.items[0].id' \
+            --raw-output)
+        
+          WR_STATUS=$(oci vn-monitoring work-request get \
+            --work-request-id "${WR_ID}" \
+            --query 'data.status' \
+            --raw-output)
+
+          oci vn-monitoring work-request-result list \
+            --work-request-id "${WR_ID}"\
+            --all \
+            --result-type PATH_ANALYSIS \
+            --output json > cms_to_web_npa_result.json
+            
+          grep reachability cms_to_web_npa_result.json
+          #####################################
+
+        
 
 
-          # echo "Work request ID: ${WR_ID}"
 
 
