used output file for oke cluster id

diff --git a/.github/workflows/terra_rm.yaml b/.github/workflows/terra_rm.yaml
--- a/.github/workflows/terra_rm.yaml
+++ b/.github/workflows/terra_rm.yaml
@@ -164,11 +164,11 @@ jobs:
     needs: plan
 
 
-    outputs:
-      oke_cluster_ocid: ${{ steps.get_rm_outputs.outputs.oke_cluster_ocid }}
-      lb_subnet_ocid: ${{ steps.get_rm_outputs.outputs.lb_subnet_ocid }}
-      lb_nsg_ocid: ${{ steps.get_rm_outputs.outputs.lb_nsg_ocid }}
-      lb_reserved_public_ip_ocid: ${{ steps.get_rm_outputs.outputs.lb_reserved_public_ip_ocid }}
+    # outputs:
+    #   oke_cluster_ocid: ${{ steps.get_rm_outputs.outputs.oke_cluster_ocid }}
+    #   lb_subnet_ocid: ${{ steps.get_rm_outputs.outputs.lb_subnet_ocid }}
+    #   lb_nsg_ocid: ${{ steps.get_rm_outputs.outputs.lb_nsg_ocid }}
+    #   lb_reserved_public_ip_ocid: ${{ steps.get_rm_outputs.outputs.lb_reserved_public_ip_ocid }}
 
 
     # This environment must be created in GitHub repo settings
@@ -1033,16 +1033,57 @@ jobs:
       #     # fi
       #     # #####################################
 
+      # - name: Read apply outputs
+      #   id: get_rm_outputs
+      #   shell: bash
+      #   env:
+      #     APPLY_JOB_ID: ${{ steps.create_apply.outputs.apply_job_id }}
+      #   run: |
+      #     set -euo pipefail
+
+      #     oci resource-manager job-output-summary list-job-outputs \
+      #     --job-id "${APPLY_JOB_ID}" \
+      #     --all \
+      #     --output json > rm_outputs.json
+
+      #     OKE_CLUSTER_OCID=$(jq -r '.data.items[] | select(."output-name"=="oke_cluster_ocid") | ."output-value"' rm_outputs.json)
+      #     LB_SUBNET_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_subnet_ocid") | ."output-value"' rm_outputs.json)
+      #     LB_NSG_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_nsg_ocid") | ."output-value"' rm_outputs.json)
+      #     LB_RESERVED_PUBLIC_IP_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_reserved_public_ip_ocid") | ."output-value"' rm_outputs.json)
+
+      #     for v in OKE_CLUSTER_OCID LB_SUBNET_OCID LB_NSG_OCID LB_RESERVED_PUBLIC_IP_OCID; do
+      #       val="${!v:-}"
+      #       if [ -z "${val}" ] || [ "${val}" = "null" ]; then
+      #          echo "ERROR: ${v} is empty or null"
+      #          exit 1
+      #       fi
+      #     done
+
+      #     cat > infra-outputs.env <<EOF
+      #     OKE_CLUSTER_OCID=${OKE_CLUSTER_OCID}
+      #     LB_SUBNET_OCID=${LB_SUBNET_OCID}
+      #     LB_NSG_OCID=${LB_NSG_OCID}
+      #     LB_RESERVED_PUBLIC_IP_OCID=${LB_RESERVED_PUBLIC_IP_OCID}
+      #     EOF
+      
+      
+      - name: Upload RM outputs artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: rm-outputs
+          path: rm-outputs.json
+
+
   create_oke_lb_service:
     name: Create OKE LoadBalancer Service
     runs-on: ubuntu-latest
     needs: apply
 
     env:
-      OKE_CLUSTER_OCID: ${{ needs.apply.outputs.oke_cluster_ocid }}
-      LB_SUBNET_OCID: ${{ needs.apply.outputs.lb_subnet_ocid }}
-      LB_NSG_OCID: ${{ needs.apply.outputs.lb_nsg_ocid }}
-      LB_RESERVED_PUBLIC_IP_OCID: ${{ needs.apply.outputs.lb_reserved_public_ip_ocid }}
+      # OKE_CLUSTER_OCID: ${{ needs.apply.outputs.oke_cluster_ocid }}
+      # LB_SUBNET_OCID: ${{ needs.apply.outputs.lb_subnet_ocid }}
+      # LB_NSG_OCID: ${{ needs.apply.outputs.lb_nsg_ocid }}
+      # LB_RESERVED_PUBLIC_IP_OCID: ${{ needs.apply.outputs.lb_reserved_public_ip_ocid }}
 
       OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
       OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
@@ -1052,6 +1093,47 @@ jobs:
       OCI_PRIVATE_KEY_PASSPHRASE: ${{ secrets.OCI_PRIVATE_KEY_PASSPHRASE }}
 
     steps:
+      - name: Download RM outputs artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: rm-outputs
+
+      - name: Parse RM outputs
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          OKE_CLUSTER_OCID=$(jq -r '.data.items[] | select(."output-name"=="oke_cluster_ocid") | ."output-value"' rm_outputs.json)
+          LB_SUBNET_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_subnet_ocid") | ."output-value"' rm_outputs.json)
+          LB_NSG_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_nsg_ocid") | ."output-value"' rm_outputs.json)
+          LB_RESERVED_PUBLIC_IP_OCID=$(jq -r '.data.items[] | select(."output-name"=="lb_reserved_public_ip_ocid") | ."output-value"' rm_outputs.json)
+
+          for v in OKE_CLUSTER_OCID LB_SUBNET_OCID LB_NSG_OCID LB_RESERVED_PUBLIC_IP_OCID; do
+            val="${!v:-}"
+            if [ -z "${val}" ] || [ "${val}" = "null" ]; then
+              echo "::error::${v} is empty or null"
+              exit 1
+            fi
+          done
+
+          echo "OKE_CLUSTER_OCID=${OKE_CLUSTER_OCID}" >> "$GITHUB_ENV"
+          echo "LB_SUBNET_OCID=${LB_SUBNET_OCID}" >> "$GITHUB_ENV"
+          echo "LB_NSG_OCID=${LB_NSG_OCID}" >> "$GITHUB_ENV"
+          echo "LB_RESERVED_PUBLIC_IP_OCID=${LB_RESERVED_PUBLIC_IP_OCID}" >> "$GITHUB_ENV"
+
+
+      - name: Load infra outputs
+        shell: bash
+        run: |
+          set -euo pipefail
+          cat infra-outputs.env
+          source infra-outputs.env
+
+          echo "OKE_CLUSTER_OCID=${OKE_CLUSTER_OCID}" >> "$GITHUB_ENV"
+          echo "LB_SUBNET_OCID=${LB_SUBNET_OCID}" >> "$GITHUB_ENV"
+          echo "LB_NSG_OCID=${LB_NSG_OCID}" >> "$GITHUB_ENV"
+          echo "LB_RESERVED_PUBLIC_IP_OCID=${LB_RESERVED_PUBLIC_IP_OCID}" >> "$GITHUB_ENV"
+
       - name: Checkout repo
         uses: actions/checkout@v4
 
