remove web2cms, cms2web npa

diff --git a/.github/workflows/terra_rm.yaml b/.github/workflows/terra_rm.yaml
--- a/.github/workflows/terra_rm.yaml
+++ b/.github/workflows/terra_rm.yaml
@@ -275,44 +275,52 @@ jobs:
 
           WEB_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
           WEB_POD_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_pod_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
+
           CMS_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
           CMS_POD_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_pod_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
+
           AIRS_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="airs_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
           AIRS_POD_TO_DB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="airs_pod_to_db_npa_test_id") | ."output-value"' rm_outputs.json)
+
           WEB_TO_REDIS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_to_redis_npa_test_id") | ."output-value"' rm_outputs.json)
           WEB_POD_TO_REDIS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_pod_to_redis_npa_test_id") | ."output-value"' rm_outputs.json)
+
           CMS_TO_REDIS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_to_redis_npa_test_id") | ."output-value"' rm_outputs.json)
           CMS_POD_TO_REDIS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_pod_to_redis_npa_test_id") | ."output-value"' rm_outputs.json)
+
           AIRS_TO_REDIS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="airs_to_redis_npa_test_id") | ."output-value"' rm_outputs.json)
           AIRS_POD_TO_REDIS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="airs_pod_to_redis_npa_test_id") | ."output-value"' rm_outputs.json)
-          WEB_TO_CMS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_to_cms_npa_test_id") | ."output-value"' rm_outputs.json)
-          CMS_TO_WEB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_to_web_npa_test_id") | ."output-value"' rm_outputs.json)
+
           NET_COMPARTMENT_ID=$(jq -r '.data.items[] | select(."output-name"=="net_compartment_id") | ."output-value"' rm_outputs.json)
 
-          if [ -z "${WEB_TO_DB_NPA_TEST_ID}" ]  = "null" ]; then
-            echo "ERROR: output web_to_db_npa_test_id not found"
-            exit 1
-          fi
+          # WEB_TO_CMS_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="web_to_cms_npa_test_id") | ."output-value"' rm_outputs.json)
+          # CMS_TO_WEB_NPA_TEST_ID=$(jq -r '.data.items[] | select(."output-name"=="cms_to_web_npa_test_id") | ."output-value"' rm_outputs.json)
+          
 
-          if [ -z "${CMS_TO_DB_NPA_TEST_ID}" ]  = "null" ]; then
-            echo "ERROR: output web_to_db_npa_test_id not found"
-            exit 1
-          fi
+          # if [ -z "${WEB_TO_DB_NPA_TEST_ID}" ]  = "null" ]; then
+          #   echo "ERROR: output web_to_db_npa_test_id not found"
+          #   exit 1
+          # fi
 
-          if [ -z "${WEB_TO_CMS_NPA_TEST_ID}" ]  = "null" ]; then
-            echo "ERROR: output web_to_db_npa_test_id not found"
-            exit 1
-          fi
+          # if [ -z "${CMS_TO_DB_NPA_TEST_ID}" ]  = "null" ]; then
+          #   echo "ERROR: output web_to_db_npa_test_id not found"
+          #   exit 1
+          # fi
 
-          if [ -z "${CMS_TO_WEB_NPA_TEST_ID}" ]  = "null" ]; then
-            echo "ERROR: output web_to_db_npa_test_id not found"
-            exit 1
-          fi
+          # if [ -z "${WEB_TO_CMS_NPA_TEST_ID}" ]  = "null" ]; then
+          #   echo "ERROR: output web_to_db_npa_test_id not found"
+          #   exit 1
+          # fi
 
-          if [ -z "${NET_COMPARTMENT_ID}" ] = "null" ]; then
-            echo "ERROR: output net_compartment_id not found"
-            exit 1
-          fi
+          # if [ -z "${CMS_TO_WEB_NPA_TEST_ID}" ]  = "null" ]; then
+          #   echo "ERROR: output web_to_db_npa_test_id not found"
+          #   exit 1
+          # fi
+
+          # if [ -z "${NET_COMPARTMENT_ID}" ] = "null" ]; then
+          #   echo "ERROR: output net_compartment_id not found"
+          #   exit 1
+          # fi
 
           echo "web_to_db_npa_test_id=${WEB_TO_DB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
           echo "web_pod_to_db_npa_test_id=${WEB_POD_TO_DB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
@@ -332,9 +340,9 @@ jobs:
           echo "airs_to_redis_npa_test_id=${AIRS_TO_REDIS_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
           echo "airs_pod_to_redis_npa_test_id=${AIRS_POD_TO_REDIS_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
 
-          echo "web_to_cms_npa_test_id=${WEB_TO_CMS_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
+          # echo "web_to_cms_npa_test_id=${WEB_TO_CMS_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
 
-          echo "cms_to_web_npa_test_id=${CMS_TO_WEB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
+          # echo "cms_to_web_npa_test_id=${CMS_TO_WEB_NPA_TEST_ID}" >> "$GITHUB_OUTPUT"
 
           echo "net_compartment_id=${NET_COMPARTMENT_ID}" >> "$GITHUB_OUTPUT"
 
@@ -361,8 +369,8 @@ jobs:
           AIRS_TO_REDIS_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.airs_to_redis_npa_test_id }}
           AIRS_POD_TO_REDIS_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.airs_pod_to_redis_npa_test_id }}
 
-          WEB_TO_CMS_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.web_to_cms_npa_test_id }}
-          CMS_TO_WEB_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.cms_to_web_npa_test_id }}
+          # WEB_TO_CMS_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.web_to_cms_npa_test_id }}
+          # CMS_TO_WEB_NPA_TEST_ID: ${{ steps.get_rm_outputs.outputs.cms_to_web_npa_test_id }}
           OCI_COMPARTMENT_OCID: ${{ steps.get_rm_outputs.outputs.net_compartment_id }}
           SUPPRESS_LABEL_WARNING: "True"
         run: |
@@ -841,7 +849,7 @@ jobs:
             --work-request-id "${WR_ID}"\
             --all \
             --result-type PATH_ANALYSIS \
-            --output json > airs_to_airs_npa_result.json
+            --output json > airs_to_redis_npa_result.json
             
           AIRS_TO_REDIS_FW_Route_NPA=$(jq -r '.data.items[0].paths[0]["forward-route"]["reachability-status"]' airs_to_redis_npa_result.json)
           AIRS_TO_REDIS_RT_Route_NPA=$(jq -r '.data.items[0].paths[0]["return-route"]["reachability-status"]' airs_to_redis_npa_result.json)
@@ -902,94 +910,94 @@ jobs:
           fi
           #####################################
 
-          ###############################
-          echo "Running NPA test for WEB-to-CMS: ${WEB_TO_CMS_NPA_TEST_ID}"
+          # ###############################
+          # echo "Running NPA test for WEB-to-CMS: ${WEB_TO_CMS_NPA_TEST_ID}"
           
-          oci vn-monitoring path-analysis get-path-analysis-persisted \
-            --path-analyzer-test-id "${WEB_TO_CMS_NPA_TEST_ID}" \
-            --wait-for-state SUCCEEDED \
-            --wait-for-state FAILED \
-            --max-wait-seconds 900 \
-            --output json > path_run.json
+          # oci vn-monitoring path-analysis get-path-analysis-persisted \
+          #   --path-analyzer-test-id "${WEB_TO_CMS_NPA_TEST_ID}" \
+          #   --wait-for-state SUCCEEDED \
+          #   --wait-for-state FAILED \
+          #   --max-wait-seconds 900 \
+          #   --output json > path_run.json
 
           
-          WR_ID=$(oci vn-monitoring work-request list \
-            --compartment-id "${OCI_COMPARTMENT_OCID}" \
-            --resource-id "${WEB_TO_CMS_NPA_TEST_ID}" \
-            --sort-by timeAccepted \
-            --sort-order DESC \
-            --limit 1 \
-            --query 'data.items[0].id' \
-            --raw-output)
+          # WR_ID=$(oci vn-monitoring work-request list \
+          #   --compartment-id "${OCI_COMPARTMENT_OCID}" \
+          #   --resource-id "${WEB_TO_CMS_NPA_TEST_ID}" \
+          #   --sort-by timeAccepted \
+          #   --sort-order DESC \
+          #   --limit 1 \
+          #   --query 'data.items[0].id' \
+          #   --raw-output)
         
-          WR_STATUS=$(oci vn-monitoring work-request get \
-            --work-request-id "${WR_ID}" \
-            --query 'data.status' \
-            --raw-output)
+          # WR_STATUS=$(oci vn-monitoring work-request get \
+          #   --work-request-id "${WR_ID}" \
+          #   --query 'data.status' \
+          #   --raw-output)
 
-          oci vn-monitoring work-request-result list \
-            --work-request-id "${WR_ID}"\
-            --all \
-            --result-type PATH_ANALYSIS \
-            --output json > web_to_cms_npa_result.json
+          # oci vn-monitoring work-request-result list \
+          #   --work-request-id "${WR_ID}"\
+          #   --all \
+          #   --result-type PATH_ANALYSIS \
+          #   --output json > web_to_cms_npa_result.json
             
-          WEB_TO_CMS_FW_Route_NPA=$(jq -r '.data.items[0].paths[0]["forward-route"]["reachability-status"]' web_to_cms_npa_result.json)
-          WEB_TO_CMS_RT_Route_NPA=$(jq -r '.data.items[0].paths[0]["return-route"]["reachability-status"]' web_to_cms_npa_result.json)
+          # WEB_TO_CMS_FW_Route_NPA=$(jq -r '.data.items[0].paths[0]["forward-route"]["reachability-status"]' web_to_cms_npa_result.json)
+          # WEB_TO_CMS_RT_Route_NPA=$(jq -r '.data.items[0].paths[0]["return-route"]["reachability-status"]' web_to_cms_npa_result.json)
           
-          echo "${WEB_TO_CMS_FW_Route_NPA}"
-          echo "${WEB_TO_CMS_RT_Route_NPA}"
+          # echo "${WEB_TO_CMS_FW_Route_NPA}"
+          # echo "${WEB_TO_CMS_RT_Route_NPA}"
 
 
-          if [ "${WEB_TO_CMS_FW_Route_NPA}" = "REACHABLE" ] && [ "${WEB_TO_CMS_RT_Route_NPA}"  = "REACHABLE" ]; then
-            echo "WEB_TO_CMS_CONNECTION IS REACHABLE"
-          else
-            echo "WEB_TO_CMS_CONNECTION IS NOT REACHABLE"
-          fi
-          #####################################
-          ###############################
-          echo "Running NPA test for CMS-to-WEB: ${CMS_TO_WEB_NPA_TEST_ID}"
+          # if [ "${WEB_TO_CMS_FW_Route_NPA}" = "REACHABLE" ] && [ "${WEB_TO_CMS_RT_Route_NPA}"  = "REACHABLE" ]; then
+          #   echo "WEB_TO_CMS_CONNECTION IS REACHABLE"
+          # else
+          #   echo "WEB_TO_CMS_CONNECTION IS NOT REACHABLE"
+          # fi
+          # #####################################
+          # ###############################
+          # echo "Running NPA test for CMS-to-WEB: ${CMS_TO_WEB_NPA_TEST_ID}"
           
-          oci vn-monitoring path-analysis get-path-analysis-persisted \
-            --path-analyzer-test-id "${CMS_TO_WEB_NPA_TEST_ID}" \
-            --wait-for-state SUCCEEDED \
-            --wait-for-state FAILED \
-            --max-wait-seconds 900 \
-            --output json > path_run.json
+          # oci vn-monitoring path-analysis get-path-analysis-persisted \
+          #   --path-analyzer-test-id "${CMS_TO_WEB_NPA_TEST_ID}" \
+          #   --wait-for-state SUCCEEDED \
+          #   --wait-for-state FAILED \
+          #   --max-wait-seconds 900 \
+          #   --output json > path_run.json
 
           
-          WR_ID=$(oci vn-monitoring work-request list \
-            --compartment-id "${OCI_COMPARTMENT_OCID}" \
-            --resource-id "${CMS_TO_WEB_NPA_TEST_ID}" \
-            --sort-by timeAccepted \
-            --sort-order DESC \
-            --limit 1 \
-            --query 'data.items[0].id' \
-            --raw-output)
+          # WR_ID=$(oci vn-monitoring work-request list \
+          #   --compartment-id "${OCI_COMPARTMENT_OCID}" \
+          #   --resource-id "${CMS_TO_WEB_NPA_TEST_ID}" \
+          #   --sort-by timeAccepted \
+          #   --sort-order DESC \
+          #   --limit 1 \
+          #   --query 'data.items[0].id' \
+          #   --raw-output)
         
-          WR_STATUS=$(oci vn-monitoring work-request get \
-            --work-request-id "${WR_ID}" \
-            --query 'data.status' \
-            --raw-output)
+          # WR_STATUS=$(oci vn-monitoring work-request get \
+          #   --work-request-id "${WR_ID}" \
+          #   --query 'data.status' \
+          #   --raw-output)
 
-          oci vn-monitoring work-request-result list \
-            --work-request-id "${WR_ID}"\
-            --all \
-            --result-type PATH_ANALYSIS \
-            --output json > cms_to_web_npa_result.json
+          # oci vn-monitoring work-request-result list \
+          #   --work-request-id "${WR_ID}"\
+          #   --all \
+          #   --result-type PATH_ANALYSIS \
+          #   --output json > cms_to_web_npa_result.json
             
-          CMS_TO_WEB_FW_Route_NPA=$(jq -r '.data.items[0].paths[0]["forward-route"]["reachability-status"]' cms_to_web_npa_result.json)
-          CMS_TO_WEB_RT_Route_NPA=$(jq -r '.data.items[0].paths[0]["return-route"]["reachability-status"]' cms_to_web_npa_result.json)
+          # CMS_TO_WEB_FW_Route_NPA=$(jq -r '.data.items[0].paths[0]["forward-route"]["reachability-status"]' cms_to_web_npa_result.json)
+          # CMS_TO_WEB_RT_Route_NPA=$(jq -r '.data.items[0].paths[0]["return-route"]["reachability-status"]' cms_to_web_npa_result.json)
           
-          echo "${CMS_TO_WEB_FW_Route_NPA}"
-          echo "${CMS_TO_WEB_RT_Route_NPA}"
+          # echo "${CMS_TO_WEB_FW_Route_NPA}"
+          # echo "${CMS_TO_WEB_RT_Route_NPA}"
 
 
-          if [ "${CMS_TO_WEB_FW_Route_NPA}" = "REACHABLE" ] && [ "${CMS_TO_WEB_RT_Route_NPA}"  = "REACHABLE" ]; then
-            echo "CMS_TO_WEB_CONNECTION IS REACHABLE"
-          else
-            echo "CMS_TO_WEB_CONNECTION IS NOT REACHABLE"
-          fi
-          #####################################
+          # if [ "${CMS_TO_WEB_FW_Route_NPA}" = "REACHABLE" ] && [ "${CMS_TO_WEB_RT_Route_NPA}"  = "REACHABLE" ]; then
+          #   echo "CMS_TO_WEB_CONNECTION IS REACHABLE"
+          # else
+          #   echo "CMS_TO_WEB_CONNECTION IS NOT REACHABLE"
+          # fi
+          # #####################################
 
         
 
